export const USERNAME = "Username/ Email";
export const PASSWORD = "Enter Password";
export const NEW_PASSWORD = "Enter Password";
export const CONFIRM_NEW_PASSWORD = "Confirm Password";
export const SIGN_UP = "SignUp";
export const SIGN_IN = "SignIn";
export const CREATE_ACCOUNT = "Create Account";
export const LIST_TITLE = "Create new list";
export const CREATE_LIST = "Create List";
export const LIST_VIEW_TASKS = "View Tasks";
export const LIST_VIEW_DELETE = "Delete List";
export const TASK_TITLE = "Create new task";
export const CREATE_TASK = "Create task"
